
server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: NutriCareBE
  ai:
    google:
      genai:
        api-key: ${AI_KEY}
        project-id: ${AI_PROJECT_ID}
        chat:
          options:
            model: gemini-2.0-flash
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
  devtools:
    restart:
      enabled: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 0
      connection-timeout: 30000
      keepalive-time: 0
      idle-timeout: 300000
      max-lifetime: 480000
      leak-detection-threshold: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
aws:
  region: ap-southeast-1
  s3:
    bucket:
      public: nutricare-public
cdn:
  base-url: https://dyfgxhmdeg59a.cloudfront.net/

jwt:
  signerKey: ${JWT_SIGNERKEY}
  valid-duration: 900
  refreshable-duration: 2592000
supabase:
  host: ${SUPABASE_HOST}
  anon-key: ${SUPABASE_ANON_KEY}
oauth:
  callback-url: ${CALLBACK_URL}
logging:
  level:
    ROOT: INFO
    com.hn.nutricarebe: DEBUG
    com.zaxxer.hikari: DEBUG